# Generated by Django 3.1.6 on 2021-04-18 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('e_mail', models.CharField(max_length=50)),
                ('pass_word', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAccount',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('dept_id', models.IntegerField()),
                ('depart_ment', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('d_o_b', models.CharField(max_length=12)),
                ('mobile_no', models.BigIntegerField()),
                ('e_mail', models.CharField(max_length=50)),
                ('pass_word', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDepartment',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Med_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_names', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.BigIntegerField()),
                ('m_name', models.CharField(max_length=100)),
                ('m_mg', models.CharField(default='5 mg', max_length=20)),
                ('m_duration', models.CharField(default='1 month', max_length=100)),
                ('p_f_name', models.CharField(default='Master', max_length=100)),
                ('p_l_name', models.CharField(default='master', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('comment', models.CharField(default='None', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_names', models.CharField(max_length=255)),
                ('l_names', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewAppointment',
            fields=[
                ('apt_id', models.AutoField(primary_key=True, serialize=False)),
                ('pat_name', models.CharField(max_length=80)),
                ('pid', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('mobile_no', models.BigIntegerField()),
                ('doc_spec', models.CharField(max_length=50)),
                ('doc_name', models.CharField(max_length=80)),
                ('apt_date', models.CharField(max_length=20)),
                ('apt_time', models.CharField(max_length=20)),
                ('book_date', models.CharField(max_length=20)),
                ('book_time', models.CharField(max_length=20)),
                ('status', models.CharField(default='Booked', max_length=30)),
                ('remark', models.CharField(default=' ', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegister',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=10)),
                ('mobile_no', models.BigIntegerField()),
                ('d_o_b', models.CharField(max_length=12)),
                ('e_mail', models.CharField(max_length=50)),
                ('pass_word', models.CharField(max_length=32)),
            ],
        ),
    ]
